---
# Install Jenkins on host
- name: Install and run Jenkins
  hosts:        jenkins_ci
  gather_facts: no
  become:       True

  tasks:
    - name: Install Prerequisites
      ansible.builtin.apt:
        pkg:
          - openjdk-11-jre
        update_cache: yes

    - name: Add Jenkins official key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins

    - name: Install Jenkins
      ansible.builtin.apt:
        name:
          - jenkins
        update_cache: yes

    - name: Describe user for pipeline jobs
      ansible.builtin.user:
        name: jenkins
        append: true
        groups: docker
        generate_ssh_key: yes
...









